git:
  depth: 1

language: node_js
addons:
  chrome: stable
cache: node_modules
node_js:
  - "8"

install: npm install

script: npm run build

after_script:
  - "node_modules/.bin/nyc report --reporter=text-lcov | node_modules/.bin/coveralls"