git:
  depth: 1

language: node_js
node_js:
  - "8"

addons:
  chrome: stable

cache: ./node_modules
install: npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
script: npm test

after_script:
  - "node_modules/.bin/nyc report --reporter=text-lcov | node_modules/.bin/coveralls"
